Moved the creation of logfile from pre-install package script to systemd init script
trezor/trezord-go pull request #246
Opened 2022-05-23 13:46 UTC by hegjon

I have not tried to build the a new rpm/deb, but replacing the existing systemd init script and running `systemctl daemon-reload` on Fedora 35 works. 

```
$ systemctl status trezord.service
● trezord.service - Trezor Bridge
     Loaded: loaded (/usr/lib/systemd/system/trezord.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2022-05-23 15:40:15 CEST; 5s ago
    Process: 309481 ExecStartPre=/usr/bin/touch /var/log/trezord.log (code=exited, status=0/SUCCESS)
    Process: 309482 ExecStartPre=/usr/bin/chown trezord:trezord /var/log/trezord.log (code=exited, status=0/SUCCESS)
    Process: 309483 ExecStartPre=/usr/bin/chmod 660 /var/log/trezord.log (code=exited, status=0/SUCCESS)
   Main PID: 309484 (trezord)
      Tasks: 8 (limit: 23797)
     Memory: 1.9M
        CPU: 40ms
     CGroup: /system.slice/trezord.service
             └─309484 /usr/bin/trezord

May 23 15:40:15 fedora systemd[1]: Starting Trezor Bridge...
May 23 15:40:15 fedora systemd[1]: Started Trezor Bridge.
May 23 15:40:15 fedora trezord[309484]: 2022/05/23 15:40:15 trezord v2.0.27 is starting.
```

Systemd init script requires full path to the executable, so it might break some special systems where the binaries are not in `/usr/bin`. 

Fedora 35:
```
$ whereis -b touch chown chmod
touch: /usr/bin/touch
chown: /usr/bin/chown
chmod: /usr/bin/chmod
```

2022-05-23 13:47 UTC, hegjon commented
Fixes #245

2022-05-23 15:02 UTC, prusnak requested changes

2022-05-23 15:02 UTC, prusnak commented on release/linux/trezord.service
> +ExecStartPre=/usr/bin/chmod 660 /var/log/trezord.log
On my system:

```
❯ which touch
/usr/bin/touch
                                                                        
❯ which chown
/usr/sbin/chown

❯ which chmod
/bin/chmod
```

2022-05-24 21:37 UTC, hegjon commented
Closing for now, I were not able to find a non-hackish way to fix this issue

2022-05-24 21:37 UTC, closed without merging